### ISSUE TITLE
IDE / Text editor integration

### ISSUE THREAD

**Issue by vrachieru** [LeCoupa/awesome-cheatsheets#13]
I've been doing the [same thing](https://github.com/vrachieru/cheatsheet) for some time now.
I've also written a small Sublime Text [plugin](https://packagecontrol.io/packages/Cheatsheet) to make things easier.
Maybe you guys could so something similar. Cheers.

**Comment by LeCoupa** [comment]
That's very interesting. Thank you for the idea. :-)
