### ISSUE TITLE
incorrect entries

### ISSUE THREAD

**Issue by nitish770** [LeCoupa/awesome-cheatsheets#177]
there's a lot of  discrepancies in python cheatsheet e.g. char, const are not valid keywords in python. int, float are not keywords there are class etc.

**Comment by LeCoupa** [comment]
Hello, thanks for letting me know. Can you submit a PR? :)

I am not very familiar with Python.

**Comment by nitish770** [comment]
would be pleasure for me.

**Comment by LeCoupa** [comment]
🎉 thank you!
