### ISSUE TITLE
I want to contribute by updating Django Cheatsheet

### ISSUE THREAD

**Issue by pranavarora1895** [LeCoupa/awesome-cheatsheets#259]
Hi, that's a great repository on cheatsheets, it's always helpful to me. Actually, there is a lot of scope in **Django cheatsheet** such as adding and registering models, fetching data from models, Django templating syntaxes, the addition of static files, templates, and their configuration in settings.py. I can apply the markdown to Django Cheatsheet as well.

**Comment by LeCoupa** [comment]
Yes sure!

**Comment by pranavarora1895** [comment]
Thanks
