### ISSUE TITLE
Curl use for scripting

### ISSUE THREAD

**Issue by silent-mobius** [LeCoupa/awesome-cheatsheets#26]
it could be useful to create a Curl cheat-sheet for scripting - major ways to use Curl.

**Comment by LeCoupa** [comment]
Yes, that's a good idea. Do you have time to start it?

**Comment by silent-mobius** [comment]
I think i can, give me access and i'll initiate the project. then we'll see how it flows.

**Comment by LeCoupa** [comment]
I added you as a collaborator. You should have access to the repository. :-)

**Comment by silent-mobius** [comment]
you wan me to work on my branch and then merge it ?

**Comment by LeCoupa** [comment]
yes you can do this :-)

**Comment by yurnov** [comment]
Hi @silent-mobius, how is your progress with curl cheat sheet?

**Comment by LeCoupa** [comment]
@yurnov feel free to make one if you have the motivation :)

**Comment by yurnov** [comment]
Here is [PR#117](https://github.com/LeCoupa/awesome-cheatsheets/pull/117)

**Comment by LeCoupa** [comment]
Awesome :)
