### ISSUE TITLE
How to temporary save data in Python?

### ISSUE THREAD

**Issue by mukeshjajoria** [LeCoupa/awesome-cheatsheets#281]
what could be the best solution to save as a draft in python. I want to save data temporary for 30 minutes for the user .what is the best process

**Comment by madseventwo** [comment]
Do you mean like if you wanted to test a small section of code with temporarily inserted variables?

Something like this..?
```
From file.py import *

var_1 = 7
var_2 = 'Name'

function_from_other_file(var_1, var_2)

print(function_from_other_file)
```
