### ISSUE TITLE
Missing favicon for the website deployed on github page .

### ISSUE THREAD

**Issue by i-dipanshu** [LeCoupa/awesome-cheatsheets#296]
@LeCoupa 
I would like to work on this issue.

**Comment by i-dipanshu** [comment]
My preferred workspace is mern stack and next.js.
Though i am not quiet familiar with nuxt.js and vue but this is a comparatively easy task , 
so i think i could get this working.

**Comment by Suraj-kumar00** [comment]
Hi everyone , i don't know can someone please tell me how can contribute here ?
