### ISSUE TITLE
React Cheat sheet

### ISSUE THREAD

**Issue by KushagraGitter** [LeCoupa/awesome-cheatsheets#33]
Create a cheat sheet for React JS

**Comment by LeCoupa** [comment]
Yes, you are right. Are you familiar with React?

**Comment by KushagraGitter** [comment]
I am learning React, i can help you as am learning i could create the cheat sheet

**Comment by LeCoupa** [comment]
Yes this would be great :)

**Comment by LeCoupa** [comment]
Here it is :-)

https://github.com/LeCoupa/awesome-cheatsheets/blob/master/frontend/react.js
