### ISSUE TITLE
Angular cheat sheet

### ISSUE THREAD

**Issue by KushagraGitter** [LeCoupa/awesome-cheatsheets#34]
Create a cheat sheet for angular 4

**Comment by LeCoupa** [comment]
Yes, you are right. Are you familiar with Angular?

**Comment by LeCoupa** [comment]
I can help you on the React one but I don't have any experience regarding Angular 4.

**Comment by aemc** [comment]
Somewhat related, would you be open to including angularjs? I can probably help with this, along with Angular.

**Comment by LeCoupa** [comment]
Closing this as someone made it: 

https://github.com/LeCoupa/awesome-cheatsheets/blob/master/frontend/angular.js
