### ISSUE TITLE
Cheatsheet C

### ISSUE THREAD

**Issue by raulvillora** [LeCoupa/awesome-cheatsheets#38]
I think it would be wonderful if you create a cheat sheet for C.

Thank you.

**Comment by LeCoupa** [comment]
Sorry but I am not familiar enough with the C programming language. Could you start it?

**Comment by raulvillora** [comment]
I have just started it. Should I create a pull request so you can review it?

**Comment by raulvillora** [comment]
I have just create a pull request.

**Comment by LeCoupa** [comment]
Perfect :-) Let me review it

**Comment by LeCoupa** [comment]
Closing the issue as I just merged #39.
