### ISSUE TITLE
C is not under Language Section in README.md

### ISSUE THREAD

**Issue by Delta456** [LeCoupa/awesome-cheatsheets#62]
Cheat sheets for C is not present in `README.md` but the file could be accessed by going to [here](https://github.com/LeCoupa/awesome-cheatsheets/blob/master/languages/C.txt)  

I want C to be added in READ.md.

**Comment by Delta456** [comment]
I though you ignored my Issue. Sorry :disappointed:

**Comment by LeCoupa** [comment]
No I'm note :)
