### ISSUE TITLE
Make the README.md more appealing

### ISSUE THREAD

**Issue by LeCoupa** [LeCoupa/awesome-cheatsheets#7]
- [ ] Encourage people to contribute.
- [x] Update the design.
- [ ] Add a code of conduct file.
- [ ] Add a contributing file.
- [ ] Preset template to keep all cheatsheets consistent.

**Comment by farisachugthai** [comment]
While we're on the topic are there any tips you'd like to mention if someone wanted to contribute? Specifically I was curious how you made your columns, how you lined them up, and if you had any recommendations for how someone could make one of these cheat sheets and have it be formatted consistently with how you do yours. Text editor plugin? Reindenting using Vim? Awk?

Thanks in advance.

**Comment by LeCoupa** [comment]
Yes, that's a good idea. I will write some recommendations for people who want to build and add their own cheatsheet to the repo.

I'm using Visual Studio Code and the columns were indented manually.

**Comment by cristijora** [comment]
Tackled second point in #11 
Just an option. Maybe it's not inline with your thoughts.

**Comment by LeCoupa** [comment]
@cristijora Yes thanks, I will merge it tonight. :-)

**Comment by LeCoupa** [comment]
@cristijora Thanks a lot for your PR! Excellent idea :-)
