### ISSUE TITLE
add canvas

### ISSUE THREAD

**Issue by Paleless** [LeCoupa/awesome-cheatsheets#77]
l think may be have a  canvas cheatsheet will be good, or just put it under javascript or html.

**Comment by LeCoupa** [comment]
I agree, if you can do it, feel free to start it in its own file. :)

**Comment by Paleless** [comment]
> I agree, if you can do it, feel free to start it in its own file. :)
l am glad to do that, but may be need a few days later  because l am kind of busy now.
if you are not in a hurry then l'm in.

**Comment by Paleless** [comment]
@LeCoupa l am glad to do that, but may be need a few days later because l am kind of busy now.
if you are not in a hurry then l'm in.

**Comment by LeCoupa** [comment]
Perfect :)

**Comment by wisdomkhan** [comment]
@Paleless by canvas cheat sheet do you mean that there should be an attractive and easy to read template incorporated in a pdf?
